version: "{build}"

image: Visual Studio 2017
configuration: Release
platform: Any CPU

clone_depth: 50

install:
 - cd %APPVEYOR_BUILD_FOLDER%
 - git submodule update --init --recursive
 - nuget restore

build:
 project: C:\Projects\ScanMsg\ScanMsg.sln
 parallel: true

on_success:
 - set APP_ZIP=%APPVEYOR_PROJECT_NAME%.zip
 - set APP_FOLDER=%APPVEYOR_BUILD_FOLDER%\ScanMsg\Build\%CONFIGURATION%
 - 7z a %APP_ZIP% %APP_FOLDER%\ScanMsg.* *.md
 - appveyor PushArtifact %APP_ZIP%
