name:        'ScanMsg'
description: 'Fallout .msg files scanner'
author:      'Rotators'
branding:
 icon:  'eye'
 color: 'green'

# Same as running: ScanMsg.exe path/to/text/
#
# uses: wipe2238/ScanMsg@master
# with:
#  path: 'path/to/text/'

# Same as running ScanMsg.exe path/to/text/ --relaxed
#
# uses: wipe2238/ScanMsg@master
# with:
#  path:    'path/to/text/'
#  relaxed: 'true'

# Same as running: ScanMsg.exe path/to/text/
#
# uses: wipe2238/ScanMsg@master
# with:
#  path:       'path/to/text/'
#  executable: 'path/to/ScanMsg.exe'

# Same as running: cd path/to/text/ && ScanMsg.exe
#
# uses: wipe2238/ScanMsg@master
# with:
#  workdir: 'path/to/text/'

inputs:
  path:
   description: ''
   required:    false
  relaxed:
   description: ''
   required:    false
   default:     'false'
  executable:
   description: ''
   required:    false
   default:     'upstream'
  workdir:
   description: ''
   required:    false
   default:     ${{ github.workspace }}


runs:
 using: 'composite'
 steps:

 - name:  Validate options
   id:    options
   run:   |
          if [[ "${{ inputs.relaxed }}" != "true" ]] && [[ "${{ inputs.relaxed }}" != "false" ]]; then
             echo "ERROR: invalid input 'relaxed' : '${{ inputs.relaxed }}'"
             echo "ERROR: available values: 'true', 'false'"
             exit 1
          fi

          if [[ ! -f "${{ inputs.executable }}" ]]; then
             if [[ "${{ inputs.executable }}" == "upstream" ]]; then
                echo "::set-output name=executable::dotnet run --project ${{ github.action_path }}/ScanMsg/ScanMsg.NET5.csproj --"
             else
                echo "ERROR: invalid input 'executable' : '${{ inputs.executable }}'"
                echo "ERROR: file does not exists"
                exit 1
             fi
          else
             echo "::set-output name=executable::${{ github.workspace }}/${{ inputs.executable }}"
          fi

          #

          if [[ "${{ inputs.relaxed }}" == "true" ]]; then
             echo "::set-output name=relaxed::--relaxed"
          fi

   shell: bash

 - name:  Run validation
   run:   |
          ${{ steps.options.outputs.executable }} ${{ inputs.path }} ${{ steps.options.outputs.relaxed }}
          rm -f ScanMsg.log
   shell: bash
   working-directory: ${{ inputs.workdir }}
   env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
