name: Action

on:
 push:
  paths:
  - '.github/workflows/Action.yml'
  - 'action.yml'
  - '**.csproj'
  - '**.cs'
 pull_request:
  paths:
  - '.github/workflows/Action.yml'
  - 'action.yml'
  - '**.csproj'
  - '**.cs'

defaults:
 run:
  shell: bash

jobs:

 Test:
  runs-on: ${{ matrix.os }}
  strategy:
   fail-fast: false
   matrix:
    os: [ windows-latest, ubuntu-latest, macOS-latest ]

  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: Empty directory
    uses: ./
    with:
     path: ScanMsg

  #

  # name: Clone RPU
  # uses: actions/checkout@v2
  # with:
  #  repository: BGforgeNet/Fallout2_Restoration_Project
  #  path:       RPU
  #
  # name: RPU (strict)
  # uses: ./
  # with:
  #  no-exitcode: true
  #  workdir:      RPU/data/text
  #
  # name: RPU (relaxed)
  # uses: ./
  # with:
  #  no-exitcode: true
  #  relaxed:     true
  #  workdir:     RPU/data/text

  #

  # name: Clone FO2T
  # uses: actions/checkout@v2
  # with:
  #  repository: BGforgeNet/FO2Tweaks
  #  path:       FO2T
  #
  # name: FO2T (strict)
  # uses: ./
  # with:
  #  no-exitcode: true
  #  workdir:      FO2T/data/text
  #
  # name: FO2T (relaxed)
  # uses: ./
  # with:
  #  no-exitcode: true
  #  relaxed:      true
  #  workdir:      FO2T/data/text
