name: Build

on:
 push:
  paths:
  - '.github/workflows/Build.yml'
  - '**.sln'
  - '**.csproj'
  - '**.cs'
  - 'App.config'
 pull_request:
  paths:
  - '.github/workflows/Build.yml'
  - '**.sln'
  - '**.csproj'
  - '**.cs'
  - 'App.config'

env:
 DOTNET_CLI_TELEMETRY_OPTOUT: true

defaults:
 run:
  shell: bash

jobs:

 Framework:
  runs-on: windows-latest

  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name:  Config
    run:   echo MSBUILD_EXE="$("/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe)" >> $GITHUB_ENV

  - name:  Build
    run:   |
           :
           "$MSBUILD_EXE" ScanMsg.sln -p:Configuration=Release -target:ScanMsg
           mv ScanMsg/Build/Framework/Release/ScanMsg.exe ScanMsg.exe

  - name:  Upload
    uses:  actions/upload-artifact@v2
    with:
     name:              ScanMsg
     if-no-files-found: error
     retention-days:    30
     path:              |
                        ScanMsg.exe
                        ScanMsg.msg
                        README.md
                        LICENSE.md

 NET5:
  runs-on: ubuntu-latest

  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: Build
    run:  |
          :
          dotnet build --configuration Release ScanMsg/ScanMsg.NET5.csproj
